### ISSUE TITLE
Several problems with Binary Objects

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_compound_parent_metadata#3]
Using this module causes several problems with the Binary Object CModel:
- Kills the child object's metadata display
- Kills the child's overall display template (including image and download link)

I'm not sure if it has a similar effect on other CModels or not.

**Comment by bondjimbond** [comment]
See https://github.com/Islandora-Labs/islandora_binary_object/issues/34 for details

**Comment by mjordan** [comment]
@bondjimbond we use Islandora Context to achieve this module's goals instead and have had no problems, although I don't recall testing Context on binary objects. I'll take a look at this module tonight.

**Comment by mjordan** [comment]
Are you seeing this error when you view the parent/first child?

![no_markup](https://user-images.githubusercontent.com/403918/53780903-522d0780-3ebb-11e9-8623-8d494f47097e.png)

**Comment by mjordan** [comment]
I think this behavior has to do with how binary objects' render arrays work. [Differently from other content models' render arrays apparently](https://github.com/Islandora/islandora/wiki/Render-arrays-in-Islandora). Basic images, for example, have a render array that contains markup that looks like you would expect:

```
Array
(
    [#markup] =>
<div class="islandora-basic-image-object islandora" vocab="http://schema.org/" prefix="dcterms: http://purl.org/dc/terms/" typeof="ImageObject">
  <div class="islandora-basic-image-content-wrapper clearfix">
[etc]
```

But binary objects' render arrays don't have any markup, it only has two keys, `#theme` and `#islandora_object`:

```
Array
(
    [0] => Array
        (
            [#theme] => islandora_binary_object
            [#islandora_object] => IslandoraFedoraObject Object
[etc]
```

So there is nothing to append the parent's metadata display to. I am not sure if this is intentional or not. 

Appending the parent's metadata display to a binary object's render array is going to fail in the [Islandora Context module too](https://github.com/SFULibrary/islandora_context/blob/7.x/islandora_context.module#L367) for this reason. I'm not sure how to make this work short of defining a custom block to render the parent's metadata in.

**Comment by mjordan** [comment]
@bondjimbond can you test the issue-3 branch to see if it resolves the issue?

**Comment by bondjimbond** [comment]
Sure, I can give it a test later... But I'm wondering if perhaps the functionality of this module is better served by https://github.com/LeidenUniversityLibrary/islandora_compound_parent_metadata_block? It does the same things, but it doesn't have the CModel-related hassles (so far as I've seen, at least).

**Comment by mjordan** [comment]
SFU hasn't used this module since the very early days, and instead we use Context (which uses some of the same code) since Context gives you a lot of control over when the parent metadata appears. I was unaware of Leiden's module. If that one suits you better, go for it. I don't know who else uses this one.

**Comment by mjordan** [comment]
Going to merge this since it resolves all three open issues with this module.
